export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';
export const CLEAR_CART = "CLEAR CART";
export const COMPLETE = "COMPLETE";
export const PRODUCTS_NAMES = {
    START_FETCH: "PRODUCTS_NAMES_START_FETCH",
    FAIL_FETCH: "PRODUCTS_NAMES_FAIL_FETCH",
    FINISH_FETCH: "PRODUCTS_NAMES_FINISH_FETCH",
    START_ADD_PRODUCT: "PRODUCTS_NAMES_START_ADD_PRODUCT",
    FAIL_ADD_PRODUCT: "PRODUCTS_NAMES_FAIL_ADD_PRODUCT",
    FINISH_ADD_PRODUCT: "PRODUCTS_NAMES_FINISH_ADD_PRODUCT"
};

export const ORDERS_NAMES = {
    START_ORDER: "START_ORDER",
    FAIL_ORDER: "FAIL_ORDER",
    FINISH_ORDER: "FINISH_ORDER",
    
}

export const CODE_NAMES = {
    START_CODE: "START_CODE",
    FAIL_CODE: "FAIL_CODE",
    FINISH_CODE: "FINISH_CODE"
}

export const PAYMENT_NAMES = {
    START_PAYMENT: "START_PAYMENT",
    FAIL_PAYMENT: "FAIL_PAYMENT",
    FINISH_PAYMENT: "FINISH_PAYMENT"
}

export const DISCOUNT_NAMES = {
    START_DISCOUNT: "START_DISCOUNT",
    FAIL_DISCOUNT: "FAIL_DISCOUNT",
    FINISH_DISCOUNT: "FINISH_DISCOUNT",
}

export const OPINION_NAMES = {
    START_ADD: "OPINION_NAMES_START_ADD",
    FAIL_ADD: "OPINION_NAMES_FAIL_ADD",
    FINISH_ADD: "OPINION_NAMES_FINISH_ADD",
}