# Generated by Django 3.0.8 on 2020-12-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
