# Generated by Django 3.1.4 on 2020-12-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
