# Generated by Django 3.1.4 on 2020-12-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
