# Generated by Django 3.1.4 on 2020-12-21 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
