# Generated by Django 3.1.4 on 2020-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_on_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_type',
            field=models.CharField(choices=[('S', 'Store'), ('O', 'Online')], max_length=1),
        ),
    ]
