# Generated by Django 3.1.4 on 2021-01-14 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20201228_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
