# Generated by Django 3.1.5 on 2021-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210124_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='./frontend/static/'),
        ),
    ]
