# Generated by Django 3.1.5 on 2021-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210125_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
